### ISSUE TITLE
 The email parameter need to be uppercase for the date of this issue

### ISSUE THREAD

**Issue by FulanoD3Tal** [ashhitch/react-use-mailchimp#1]
Hello, I tried to use your hook but couldn't cause an all uppercase input's name condition, the problem is in the main file where you are destructive the input object and try to validate the email if I try to send and input with the name **EMAIL**

Transform email or all the inputs to uppercase just before send will fix the problem without force current users of this package to update their code

**Comment by ashhitch** [comment]
V2.0.0 resolves this issue
