### ISSUE TITLE
Always 'Failed to subscribe' but subscribes anyway (CORS)

### ISSUE THREAD

**Issue by OddBlueDog** [ashhitch/react-use-mailchimp#2]
Is this expected behaviour when using this on client side? I always get 'Failed to subscribe' as there is a CORS error on the latest version of Chrome, but it subscribes the person anyway. 

The browser I'm using is **Chrome v89** (https://developers.google.com/web/updates/2020/07/referrer-policy-new-chrome-default)

"Referrer Policy: strict-origin-when-cross-origin"

How do other people handle this? I'm going to assume the subscription was successful in all cases and ignore the CORS error.

**Comment by ashhitch** [comment]
V2.0.0 solves this issue
